// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiqxywhaggmjrbtvkanm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpcXh5d2hhZ2dtanJidHZrYW5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTk2MDMsImV4cCI6MjA2MDIzNTYwM30.eze2bmFbHwsqxXP3vkUVqi-rPH3NQlFlJ-xRh0QihCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);